name: Actualizar Tasas BCV
on:
  schedule:
    # 0 21 * * * significa: Todos los días a las 21:00 UTC
    # Como Venezuela es UTC-4, esto son las 5:00 PM VET
    - cron: '0 21 * * *'
  workflow_dispatch: # Esto permite que tú lo ejecutes manualmente cuando quieras probarlo

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # IMPORTANTE: Permite que el script suba cambios al repo
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install requests beautifulsoup4

      - name: Ejecutar script
        run: python actualizar_tasas.py

      - name: Subir cambios
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto: Actualizacion tasas ${{ github.run_id }}" || exit 0
          git push