name: Actualizar Tasas BCV

on:
  schedule:
    # Programación en UTC (VET + 4 horas)
    # 4:01 PM VET -> 20:01 UTC
    - cron: '1 20 * * *'
    # 4:05 PM VET -> 20:05 UTC
    - cron: '5 20 * * *'
    # 4:10 PM VET -> 20:10 UTC
    - cron: '10 20 * * *'
    # 5:00 PM VET -> 21:00 UTC
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install requests beautifulsoup4

      - name: Ejecutar script
        run: python actualizar_tasas.py

      - name: Subir cambios
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          # Solo hace commit si hay cambios detectados
          if ! git diff --cached --exit-code; then
            git commit -m "Auto: Actualizacion tasas ${{ github.run_id }}"
            git push
          else
            echo "Sin cambios, todo está al día."
          fi